// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYK3omwDOYxVkJHFdULpbZLv6yxwFcxk8',
    appId: '1:982947529011:android:5585c72dac36c7322ebe46',
    messagingSenderId: '982947529011',
    projectId: 'bonikbazar-b19dd',
    storageBucket: 'bonikbazar-b19dd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSctVUAAN4sxw0LsbRIqANZsIMNsw8X5E',
    appId: '1:982947529011:ios:bdc596549c226c6b2ebe46',
    messagingSenderId: '982947529011',
    projectId: 'bonikbazar-b19dd',
    storageBucket: 'bonikbazar-b19dd.appspot.com',
    androidClientId: '982947529011-gecj7jjup8l4d44lfmg7e93tcjicmfrb.apps.googleusercontent.com',
    iosClientId: '982947529011-c45q6sneg6ji6vc51dtunnohfmo5c5d1.apps.googleusercontent.com',
    iosBundleId: 'com.eclassify.wrteam',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRVZ1nkqmjoW8-hDw0imLMoKyVOwH-NA0',
    appId: '1:982947529011:web:e49bf23a530a03432ebe46',
    messagingSenderId: '982947529011',
    projectId: 'bonikbazar-b19dd',
    authDomain: 'bonikbazar-b19dd.firebaseapp.com',
    storageBucket: 'bonikbazar-b19dd.appspot.com',
    measurementId: 'G-ZE01BZ6ZEE',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSctVUAAN4sxw0LsbRIqANZsIMNsw8X5E',
    appId: '1:982947529011:ios:17d2e49d6720af422ebe46',
    messagingSenderId: '982947529011',
    projectId: 'bonikbazar-b19dd',
    storageBucket: 'bonikbazar-b19dd.appspot.com',
    androidClientId: '982947529011-gecj7jjup8l4d44lfmg7e93tcjicmfrb.apps.googleusercontent.com',
    iosClientId: '982947529011-6i4eu6ogvq5e4ngbrpuaofvr7k1jfkej.apps.googleusercontent.com',
    iosBundleId: 'com.eclassify.eclassify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCRVZ1nkqmjoW8-hDw0imLMoKyVOwH-NA0',
    appId: '1:982947529011:web:f57ed9fceddbe0362ebe46',
    messagingSenderId: '982947529011',
    projectId: 'bonikbazar-b19dd',
    authDomain: 'bonikbazar-b19dd.firebaseapp.com',
    storageBucket: 'bonikbazar-b19dd.appspot.com',
    measurementId: 'G-9SS4X5BRT7',
  );

}